"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _song from './song.bones.json'

configureBoneyard({"animate":"shimmer"})

registerBones({
  "song": _song,
})
